dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.3
  - 2.5.1
  - ruby-head

before_install:
  - gem install bundler
  - gem update --system

matrix:
  allow_failures:
    - rvm: ruby-head

script: bundle exec rspec
